### ISSUE TITLE
When using the "after" filter, it will properly count results but not download them

### ISSUE THREAD

**Issue by tokenwizard** [achillean/shodan-python#154]
Is anyone else experiencing this behavior?

`shodan count "country:us port:554 after:01/06/2021"`
`219035`

But if you then try to download those results, it does return the same number of results but then does not download any:
`shodan download US_port554 "country:us port:554 after:01/06/2021"`
`Search query:			country:us port:554 after:01/06/2021`
`Total number of results:	219035`
`Query credits left:		100`
`Output file:			US_port554.json.gz`
`Notice: fewer results were saved than requested`
`Saved 0 results into file US_port554.json.gz `

If I remove the "after" filter from the operation, it download fine (the first 1000 results by default).

So it seems that adding the "after" filter to the download command breaks the download operation somehow. I am able to download all day long if I leave that filter out. Unfortunately, since they results seem to be coming down sorted by IP, I am getting a mix of some very old results and it is difficult to look at only more recent results.

**Comment by achillean** [comment]
The ``after`` filter isn't officially supported anymore so for now it's only available in subscription API plans for legacy support. I'm guessing your account doesn't have a subscription (i.e. you have a membership) which is why that search filter doesn't work.

The ``before`` and ``after`` filters are misleading because it makes people think that Shodan indexes historical data - we don't. So using those filters doesn't let you search/ download data from a long time ago. It can be helpful for creating daily data files of new search results but you can do that without those filters as well. Just write a small Python script that parses the ``timestamp`` property on the banner and stops iterating results once the previous day has been reached.
