### ISSUE TITLE
 Access denied (403 Forbidden)

### ISSUE THREAD

**Issue by madella** [achillean/shodan-python#187]
with `ApiShodan($KEY).api.host($IP)`
i get always :
```
/lib/python3.11/site-packages/shodan/client.py", line 338, in _request
    raise APIError('Access denied (403 Forbidden)')
shodan.exception.APIError: Access denied (403 Forbidden)
```
even if i try to change API key, and also when i try to use friend's api_key

**Comment by Mponge** [comment]
I got same issue. 

Any ideas ?

**Comment by EmaEusepi** [comment]
Same problem here...

**Comment by federica-fabbri** [comment]
Same problem, please fix

**Comment by Mponge** [comment]
Hi all, I contact the support and now WE have to pay one Time 50 dollars, due to abuse, check answer:


Sorry for the inconvenience. Due to abuse we now require accounts to have at least a membership in order to run search queries. The account you're using is a free account which is why you're now seeing the 403 error message. Note that a Membership is a one-time payment of $49 (i.e. not a subscription):

https://account.shodan.io/billing/member

Regards,

**Comment by madella** [comment]
So, this API  project has become useless without paying? What a wonderful open-source project! 

> Hi all, I contact the support and now WE have to pay one Time 50 dollars, due to abuse, check answer:
> 
> Sorry for the inconvenience. Due to abuse we now require accounts to have at least a membership in order to run search queries. The account you're using is a free account which is why you're now seeing the 403 error message. Note that a Membership is a one-time payment of $49 (i.e. not a subscription):
> 
> https://account.shodan.io/billing/member
> 
> Regards,

**Comment by achillean** [comment]
Yes, for now we've had to take this measure to limit IP lookups and searches to users that have at least a Membership. As an alternative for free IP lookups you can check out:

https://internetdb.shodan.io

**Comment by Packjackisback** [comment]
Will this ever return?
