### ISSUE TITLE
CVE number as a property in output

### ISSUE THREAD

**Issue by sjorsng** [achillean/shodan-python#33]
It would be nice if search results have an optional property of a CVE number where the result is affected by. I know there is a filter available for that (example: vuln:cve-2014-0160) but in the output the results contain no clue of that CVE number.   
Also: is there any list available of currently supported CVE numbers detected by Shodan?

**Comment by achillean** [comment]
The CVE values are stored in the **opts.vulns** property on the banner which is where the website pulls the information from (the website is powered by the API). And to get a list of currently-tested vulnerabilities and their CVE values you can use the **vuln** facet. Here's a command-line solution for getting the list:

`shodan stats --facets vuln net:0/0`

Note that vulnerabilities starting with a "!" mean that the given service is NOT vulnerable to the CVE. I.e. a value of "!cve-2014-0160" means the service is NOT vulnerable to Heartbleed. We only add the "!" for a few vulnerabilities that we added a long time ago and aren't doing this anymore for the new ones being added. But we're keeping the "!" values around since a few customers depend on it and we want to maintain backwards-compatibility.
