### ISSUE TITLE
Blank page when using Search option in CLI

### ISSUE THREAD

**Issue by razermouse** [achillean/shodan-python#62]
Using the Host option works as expected. However, when I try to use Search to narrow down on a specific set of fields, all I get is an empty (blank) page with no data. At the bottom left corner, the page shows "lines 1-1/1 (END)".

**Comment by achillean** [comment]
Please provide a sample CLI command to help us reproduce the problem. Are you using search filters? Is this using a free account? Maybe it errored out and the CLI wasn't showing a good error?

**Comment by razermouse** [comment]
Yes, I am using a free account and using filters. By the way, I'm on OpenSUSE. This actually worked until I updated to what was at the time the most current OS version.  

Linux rip 4.4.27-2-default #1 SMP Thu Nov 3 14:59:54 UTC 2016 (5c21e7c) x86_64 x86_64 x86_64 GNU/Linux

It happens on any IP. Example CLI command and attached image of what I see.

# shodan search --fields asn,ip_str,port 98.138.252.38

![blank_search](https://user-images.githubusercontent.com/11528955/36175616-bcfc8884-10d5-11e8-93f2-93ce093ee56b.png)

**Comment by achillean** [comment]
Thanks! It looks like your search query isn't returning any results which is why you're seeing an empty screen. If you do the following command then you will see results, though it requires a paid Shodan account (membership or higher):

    shodan search --fields asn,ip_str,port net:98.138.252.38

The CLI should be changed to show a message when there aren't any results instead of a blank screen.

**Comment by achillean** [comment]
Also note that this is one of the few areas where the Shodan website behaves differently/ smarter: if a user searches for an IP address then it automatically adds a "net:" filter in front of the query which is why your search query works on the website but not the API/ CLI.

**Comment by razermouse** [comment]
You learn something new everyday. Very nice!  

I did not know about the net: filter being required for a single IP. I mistakenly thought I could simply specify the IP. That's how a lot of command line tools seem to work (e.g., nmap). 

May I suggest an update to the Guide?  The net filter says "Network range in CIDR notation (ex. 199.4.1.0/24)".

**Comment by achillean** [comment]
The "shodan host" command is designed for single IP lookups - it's faster and provides friendlier output.

The API tries to have consistent behavior and leave it up to the developer to add any special/ optimized ways of handling user input. Without filters, the provided text is searched for in the banners themselves. For example, how would you find service banners that contain that IP but the services are running on another IP? That situation actually comes up more than expected which is why the API behaves the way it does. We should find a way though to make that a bit clearer in the documentation.
