### ISSUE TITLE
Shodan CLI ports - inconsistency

### ISSUE THREAD

**Issue by razermouse** [achillean/shodan-python#63]
In some cases the Shodan CLI will report an accurate count of what it knows regarding Open ports. But then what it lists below in the Ports section doesn't match up with the count. 

Example 1:

Number of open ports:    8

Ports:
   2082  
   2083  
	|-- SSL Versions: TLSv1, TLSv1.1, TLSv1.2
   2086  
   2087  
	|-- SSL Versions: TLSv1, TLSv1.1, TLSv1.2
   8080  
   8880

Missing: 443 and 8443. The UI shows all 8.

Example 2:

Number of open ports:    9
Vulnerabilities:         CVE-2015-0204	CVE-2015-4000

Ports:
     22 OpenSSH (5.3)
     53  
     53  
     80 Apache httpd (2.2.15)
    465  
	|-- SSL Versions: TLSv1, TLSv1.1, TLSv1.2
	|-- Diffie-Hellman Parameters:
		Bits:          2048
		Generator:     2
    587  
	|-- SSL Versions: TLSv1, TLSv1.1
    636  
	|-- SSL Versions: SSLv3, TLSv1, TLSv1.1, TLSv1.2
	|-- Diffie-Hellman Parameters:
		Bits:          2048
		Generator:     2
    993  
	|-- SSL Versions: SSLv3, TLSv1, TLSv1.1, TLSv1.2
	|-- Diffie-Hellman Parameters:
		Bits:          1024
		Generator:     2
		Fingerprint:   RFC2409/Oakley Group 2

 Missing: 8443. The UI shows all 9.

**Comment by achillean** [comment]
If your Shodan account hasn't been upgraded then you won't see the banners for ports 443/ 8443 which is why they don't show up in the CLI. However, the ports are listed in the top-level **ports** property to let you know that they're open. If you were accessing it using a non-free API plan then you wouldn't see this issue.

The CLI should be adjusted to show all open ports and show the details if possible.
